[package]
name = "custom_logger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log =  "0.4.14"
syslog = "6.0.1"